# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b89e3e3d45a896f07a342d98ac6d6610bcb226c69f4ddbdca62c389c841100c1d49371345f9016b6a8aad941f316a99d571090ab51de770977ab6ea5ebdc117

test:
  secret_key_base: db0a67e3b219cd1df0bff96fd2049c017deced2309341a1fe7edc7c29731b793db6373102759f511783fd7d679551649ee7174e28bf8a0fa16b38ea9431eb9d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
